version: '4.2'
services:
  bin:
    container_name: ThreeCli
    env_file: .env
    build: .
    depends_on:
      - mongo-docker-service
      - redis-docker-service
  mongo-docker-service:
    env_file: .env
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INIT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INIT_PASSWORD}
      DB_URI: ${DB_URI}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongo:/data/db
  redis-docker-service:
    env_file: .env
    image: redis:latest
    ports:
    - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
    - redis:/data
    command: ["redis-server"]

volumes:
  mongo:
    driver: local
  redis:
