import { type AppRouter } from "../../route/routeur.js";
import { type Express } from "express";
export declare class ServerHandler {
    private static _socketHandlerInterface;
    private static _iteratorAggregate;
    private _server;
    private _app;
    private static _proxy;
    private _redisClient?;
    private _port;
    private readonly _target;
    private _subject;
    constructor(data: AppRouter[], subject: LibFile.Subject, app: Express, port: number);
    private setRedisclient;
    private fourdigitPort;
    private serverProxyHandler;
    private static accessAppRouterHandle;
    private static handleSocketType;
    private createRoute;
    private serverWatcher;
    private initWatcher;
    private setFile;
    private getFile;
    private tryPort;
    private setApp;
    private setServer;
    private setCallBacks;
    private dataCallBack;
    private endCallBack;
    private errorCallBack;
    private upgradeServeur;
    private startServerCallBack;
    run(): void;
    shutDown(output: string): void;
}
