export default class Compile {
    constructor(compilerDir?: string);
    fileDirArray: string[];
    mapAsset: Map<any, any>;
    setAllConstant(text: any): void;
    addToAllConstant(...array: any[]): void;
    getfileDirarraySlice(start: any, end: any): string[];
    get allConstant(): any[];
    setMapFile(fileArray: string[]): string[];
    public replaceContent(text: string, arrayWord: Array<string>, objNameSpace: Array<string>): string;
    nameSpaceMaker(file: string): string;
    public checkdouble(array: string): Compiler.double;
    public getTotaldeclaration(text: string): Compiler.declarations;
    getClassDeclaration(text: any): Compiler.classDeclaration;
    getContentFile(fileArray: string[]): Promise<string>;
    ObjectNamespaceMakerPromise(array: any, file: any): Promise<string | null>;
    doubleDeclarationHandler(array: any, file: any): Promise<any>;
    public getComposerContent(fileArray: string[]): Promise<string>;
    ContentCleaner(contentRaw: string, totalConstant: string[], asset: string[]): Promise<string>;
    formatName(pathfile: string, prefix: null | string, suffix?: string): string;
    classModifyGenerator(arrayClass: string[]): Generator<string, void, unknown>;
    regexChangerConst(word: string): RegExp;
    cleanerCommunJsDeclaration(text: string): string;
    DeletorForClassPromise(text: string): Promise<any>;
    replacorForFunctionPromise(text: string): Promise<Compiler.remplace>;
    public lazyRemplacement(beginingFile: any, endFile: any): void;
    lazyComposerRemplacement(beginingFile: string, endFile: string): Promise<void>;
    regexSectionMaker(toSection: string): RegExp;
    regexSectionMakerForClass(toSection: string): RegExp;
    public repopulateComposer(file: string, composerContext?: boolean): Promise<void>;
    public repopulatelinkFile(file: string, composerContext?: boolean): Promise<void>;
    removeAllBlank(text: string): string;
    public getAllExportName(content: string): string[];
    public addimportScript(file: string): void;
    public getExportScript(constArray: any): string;
    public getImportStript(jumpLine?: boolean): string;
    public getAssetPathConst(): object;
    public getConfigUtilty(): any;
    public getImportCommunJsScript(): string;
    getImportEsmScript(): string;
    public compilerContentPromise(arrayFile: string[], typedata?: string): Promise<string>;
    #private;
}
